/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
  theme: {
    extend: {
      // --- Brand palette (light SaaS: blue → indigo → purple) ---
      colors: {
        brand: {
          DEFAULT: '#2563EB',
          dark: '#1e40af',
          light: '#3b82f6',
        },
        // Legacy ink scale — kept so any stragglers still resolve.
        ink: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        // Light surface scale (Material-like, re-mapped to a light theme).
        background: '#F8FAFC',
        surface: '#F8FAFC',
        'surface-dim': '#F1F5F9',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#F8FAFC',
        'surface-container-low': '#FFFFFF',
        'surface-container': '#F1F5F9',
        'surface-container-high': '#E2E8F0',
        'surface-container-highest': '#CBD5E1',
        'surface-variant': '#E2E8F0',
        'on-surface': '#0F172A',
        'on-surface-variant': '#475569',
        'on-background': '#0F172A',
        'border-subtle': '#E2E8F0',
        outline: '#94A3B8',
        'outline-variant': '#CBD5E1',
        // Brand / accent tokens.
        primary: '#2563EB',
        'primary-container': '#DBEAFE',
        'on-primary': '#FFFFFF',
        'primary-fixed': '#DBEAFE',
        'on-primary-container': '#1e3a8a',
        secondary: '#7C3AED',
        'secondary-container': '#EDE9FE',
        'on-secondary': '#FFFFFF',
        tertiary: '#06B6D4',
        'tertiary-container': '#CFFAFE',
        'on-tertiary': '#FFFFFF',
        error: '#DC2626',
        'error-container': '#FEE2E2',
        'on-error': '#FFFFFF',
        'on-error-container': '#7f1d1d',
        // Signature accents (used for gradients + link color).
        'neon-blue': '#2563EB',
        'electric-purple': '#7C3AED',
        accent: '#06B6D4',
        'glass-highlight': 'rgba(255, 255, 255, 0.6)',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
      },
      fontSize: {
        'code-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        'body-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'body-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'title-md': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-lg': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'headline-xl': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'label-caps': ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        'code-sm': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
    },
  },
  plugins: [],
};
