/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
  theme: {
    extend: {
      // --- Original brand palette (kept for backwards-compat) ---
      colors: {
        brand: {
          DEFAULT: '#1d4ed8',
          dark: '#1e3a8a',
          light: '#3b82f6',
        },
        ink: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
        // Material-like dark surface scale.
        background: '#0c1322',
        surface: '#0c1322',
        'surface-dim': '#0c1322',
        'surface-bright': '#323949',
        'surface-container-lowest': '#070e1d',
        'surface-container-low': '#141b2b',
        'surface-container': '#191f2f',
        'surface-container-high': '#232a3a',
        'surface-container-highest': '#2e3545',
        'surface-variant': '#2e3545',
        'on-surface': '#dce2f7',
        'on-surface-variant': '#c3c6d7',
        'on-background': '#dce2f7',
        'border-subtle': '#1E293B',
        outline: '#8d90a0',
        'outline-variant': '#434655',
        // Brand / accent.
        primary: '#b4c5ff',
        'primary-container': '#2563eb',
        'on-primary': '#002a78',
        'on-primary-container': '#eeefff',
        'primary-fixed': '#dbe1ff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'inverse-primary': '#0053db',
        'surface-tint': '#b4c5ff',
        'inverse-surface': '#dce2f7',
        'inverse-on-surface': '#293040',
        secondary: '#d0bcff',
        'secondary-container': '#571bc1',
        'on-secondary': '#3c0091',
        'on-secondary-container': '#c4abff',
        'secondary-fixed': '#e9ddff',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary-fixed': '#23005c',
        'on-secondary-fixed-variant': '#5516be',
        tertiary: '#ffb596',
        'tertiary-container': '#bc4800',
        'on-tertiary': '#581e00',
        'on-tertiary-container': '#ffede6',
        'tertiary-fixed': '#ffdbcd',
        'tertiary-fixed-dim': '#ffb596',
        'on-tertiary-fixed': '#360f00',
        'on-tertiary-fixed-variant': '#7d2d00',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        // Neon accents (the mockup's signature look).
        'neon-blue': '#3B82F6',
        'electric-purple': '#A855F7',
        'glass-highlight': 'rgba(255, 255, 255, 0.05)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
      },
      fontSize: {
        'code-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
